### PR TITLE
Update to FLAC 1.3.4

### PR DESCRIPTION
**Pull request by mgeier**
See https://github.com/xiph/flac/releases/tag/1.3.4

### CODE REVIEW

**Comment by mgeier** [comment]
The Windows error sounds like https://github.com/xiph/flac/pull/248 and https://github.com/xiph/flac/pull/267.

**Comment by dheijl** [comment]
I checked out the flac-update branch and ran:

```
git submodule update --remote --merge
cd bindgen
./run-bindgen.sh
cd ..
cargo build && cargo build --release
```
both on Windows MSVC and Linux without any problems.
Unfortunately I don't have MinGW to test.

Is it possible that this has been solved and that the update to flac 1.3.4 can proceed?

**Comment by mgeier** [comment]
The problem only happens on Windows/MinGW and it is not yet fixed in FLAC 1.3.4 (but I think it is fixed in the `master` branch).

Would you like to ask for a new FLAC release?

**Comment by dheijl** [comment]
Thanks for the clarification! 
I don't mind waiting for a new Flac release that fixes it as I currently don't experience any problems with the 1.3.3 release I'm using now. 
Do you think that I should open an issue asking for a new release?

**Comment by mgeier** [comment]
> Do you think that I should open an issue asking for a new release?

Yes, I think it would be good to make the FLAC maintainers aware that we are waiting for a release.

**Comment by dheijl** [comment]
Done: https://github.com/xiph/flac/issues/403.

**Comment by mgeier** [comment]
I've tried manually applying the MinGW commits in #24, but it doesn't work yet ... any ideas how to make it work?

**Comment by mgeier** [comment]
Version 1.4.2 is now available (#26), I'm closing this.

If somebody specifically needs versions 1.3.4, please leave a comment here.

**Pull request closed without merging**
