### PR TITLE
Fix build on MSYS2, probably speed it up everywhere

### PR DESCRIPTION
**Pull request by nabijaczleweli**
See commit message for detail

Ref: https://github.com/nabijaczleweli/flac-bound/pull/2

### CODE REVIEW

**Comment by mgeier** [comment]
Cool, I didn't know the `build_target()` method!

Now there seems to be a CI error in the MSVC build, do you know what's the problem there?

**Comment by nabijaczleweli** [comment]
Not a clue, besides the linker not finding the library for some reason. Can't really test that ABI myself, nor do I know much about the toolchain conventions.

**Comment by mgeier** [comment]
OK, I tried quite a few things, and I finally found it:

```rust
    println!(
        "cargo:rustc-link-search=native={}/build/src/libFLAC/Debug",
        flac_path.display()
    );
```

I guess in release builds this will end with `Release`.
We should either test which mode we are in, or just add both paths, since additional unused paths don't hurt.

Can you please also run `cargo fmt` to get rid of the other error?

**Comment by nabijaczleweli** [comment]
Alright, I've special-cased MSVC to use the build profile at the end. The code for build profile detexion is stolen from cmake-rs, but I've opened https://github.com/alexcrichton/cmake-rs/pull/105 to extract it and possibly migrate thereto later.

**Comment by mgeier** [comment]
Thanks a lot @nabijaczleweli!

I hope we can get rid of the duplicated code soon when `cmake-rs` has a new release.

**Comment by mgeier** [comment]
Coming back to the question whether unused paths hurt or not (see https://github.com/mgeier/libflac-sys/pull/5#issuecomment-723695006) ...

I didn't notice this before, but the `flac_path` would start with `target/debug/build/` or `target/release/build/`, right?

So there can never be any confusion, because `cmake` will always create `Debug` within `../debug/..` and `Release` within `../release/..`, right?

If this is true, and I think it is, we wouldn't actually need the complicated check for `Debug` vs `Release`, we could just define both:

```rust
    println!(
        "cargo:rustc-link-search=native={}/build/src/libFLAC/Debug",
        flac_path.display()
    );
    println!(
        "cargo:rustc-link-search=native={}/build/src/libFLAC/Release",
        flac_path.display()
    );
```

Or am I missing something?

**Comment by nabijaczleweli** [comment]
It wouldn't change much, but you *are* missing at least two other build profiles, yes. At any rate, this shouldn't change much since, well, the last `cmake-rs` release was in May and my PR was the first and only commit to the default branch since then, so maybe if I just ask @alexcrichton nicely he'll publish 0.1.45, please?

**Comment by mgeier** [comment]
Right, I forgot about those two exotic-sounding profiles ... so I agree, we should wait for Alex making a new release.

**Comment by alexcrichton** [comment]
Sure thing, published!

**Comment by nabijaczleweli** [comment]
dope

**Pull request merged**
